### ISSUE TITLE
새로운 m4a 파일을 asset 에 추가하여 사용할 수 없음

### ISSUE THREAD

**Issue by kjunu** [KimGunSoo/sosohanapp#4]
01-18 16:44:09.868 15022-15032/com.sosohan.snapmv V/MediaPlayer: notify(8, 0, 0) callback on disconnected mediaplayer
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv E/MediaPlayer: Unable to create media player
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv D/SelectBgmActivity: playBGM() fail : IOException
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err: java.io.IOException: setDataSourceFD failed.: status=0x80000000
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.media.MediaPlayer._setDataSource(Native Method)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1292)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1277)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at com.sosohan.snapmv.SelectBgmActivity$3.playBGM(SelectBgmActivity.java:196)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at com.sosohan.snapmv.SelectBgmActivity$3.onItemClick(SelectBgmActivity.java:184)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.widget.AdapterView.performItemClick(AdapterView.java:334)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.widget.AbsListView.performItemClick(AbsListView.java:1531)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3667)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.widget.AbsListView.onTouchUp(AbsListView.java:5605)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.widget.AbsListView.onTouchEvent(AbsListView.java:5371)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.View.dispatchTouchEvent(View.java:8968)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2698)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2410)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5308)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2568)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1776)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:2866)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2529)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.View.dispatchPointerEvent(View.java:9173)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4706)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4544)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4201)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4258)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6564)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6454)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6425)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6654)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:143)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.os.Looper.loop(Looper.java:130)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5942)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
01-18 16:44:09.908 15022-15022/com.sosohan.snapmv W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by kjunu** [comment]
왜인지 모르겠지만 해결됨
